### ISSUE TITLE
Formatted message incorrect

### ISSUE THREAD

**Issue by bfv** [daleghent/nina-ground-station#12]
The following message: 
```
t=$$FORMAT_DATETIME_UTC yyy-mm-ddTHH:mm:ssZ$$, Tcam=-10°C, Tamb=$$WX_AMBTEMP$$
```
is expanded into: 
``` 
t=2024-18-29T15:18:53$Z, Tca18=-10°C, Ta18b=$WX_A2BTE2P
```
So the token expansion is not performing inside the `$$FORMAT_DATETIME_UTC yyy-mm-ddTHH:mm:ssZ$$`

Edit: version is `1.15.1.0`

**Comment by bfv** [comment]
btw, there's a reasonable workaround by simply putting the `T=` part on the next line.

**Comment by daleghent** [comment]
Thanks for the report. I'll look into this soon. There must be something particularly tricky about .NET8 regex that isn't obvious; the regex that is used to find the `$$FORMAT_DATE ...$$` token and extract the specifier works fine on regex101's C# simulator, but here it is inserting some gibberish into unrelated areas of the same line as well. I'm not sure why the line break changes its behavior. I'll do some tests to try to find out.

**Comment by daleghent** [comment]
This should address it 063ecffc9029ce6ee1c458f1f467d7aa7abca077

The regex was being too greedy when extracting the specifier string from the token when there was another token on the same line. As a result it was including the entire other token in the string specifier (and everything in between) up until the last `$$`.

GS 2.4.0 is up now. Try it and let me know how it works out.

**Comment by bfv** [comment]
I just checked 2.4.0.0 in NINA 3.0 RC002 and indeed this works as expected. My "production server" is still running NINA 2.3 HF2 and if I'm correct 2.4.0.0 is not available there, so I'll have to wait till that's out of beta. Thanks for the swift response/fix!
AFAIC this issue can be closed (don't know what your workflow is).
