### ISSUE TITLE
connection to itfff

### ISSUE THREAD

**Issue by eriktim82** [daleghent/nina-ground-station#13]
having an issue where itfff isn't working correctly.

suggestions?

**Comment by eriktim82** [comment]
I'm not getting any ifttt notifications.

I've setup the correct web hook.

It was working fine before my transition to windows 11.

**Comment by eriktim82** [comment]
Can you direct me to how to get a log file?

Yes I have everything set up correctly in Nina.

**Comment by daleghent** [comment]
There is a button in Options > General > Advanced that will open a File Explorer window in the directory where NINA maintains its logs. One log file from a session where this behavior happened would suffice for now.

**Comment by eriktim82** [comment]
[20240405-205650-3.0.0.9001.9304-202404.log](https://github.com/daleghent/nina-ground-station/files/14962765/20240405-205650-3.0.0.9001.9304-202404.log)
 here is my log file that was requested

**Comment by daleghent** [comment]
It appears that this is because you don't have an IFTTT Pro account. IFTTT made a sudden and not widely-announced change in February that moved Webhooks from their free tier to the Pro tier. Pro tier pricing is currently $35/year and signing up for that will give you access to it once again.
