### ISSUE TITLE
Feature request: Have a way to include the "description" of HTTP requests included in payload

### ISSUE THREAD

**Issue by jamiesmith** [daleghent/nina-ground-station#14]
Since IFTTT moved the webhooks to a paid tier I've been using a simple HTTP POST to send data to slack.

It would be great if there were a way to include something like `$$HTTP_DESCRIPTION$$` as part of the payload.

Right now I'm basically doing this:

- Desc: Fell out of Safe to image
- Method: POST
- URL: <slack hook endpoint>
- type: application/json
- Body: 
```
{
  "text": "Fell out of Safe to image  [$$INSTRUCTION_SET$$]"
}
```

Which means I have to open and edit each one. If there were a macro for the description it could instead have the body of 
```
{
  "text": "$$HTTP_DESCRIPTION$$  [$$INSTRUCTION_SET$$]"
}
```

and then I'd never need to change the details, just the description

Thank you for considering, and THANK YOU for the plugin!

**Comment by daleghent** [comment]
Sure I've added a `$$DESCRIPTION$$` token for the **Send HTTP Request** instruction. It will be available in GS 3.0 which is currently under development.
