### ISSUE TITLE
Why are MQTT messages always retained?

### ISSUE THREAD

**Issue by giangitesta** [daleghent/nina-ground-station#15]
Hello, 
I would like to better understand the MQTT message sending mode that GroudStation uses.
Basically, if I try to post any MQTT message it is always kept (RETAINED) without me being able to avoid it.
This implies that any notification or command I send is maintained and re-executed upon subscribing to that topic. Ideally, I would like to be able to choose from UI whether or not to retain the message. 
Best regards 
G

**Comment by giangitesta** [comment]
Okay, I had inferred this from reading the source code. To make myself more clear, I'll explain my scenario. During a session I use various messages to Home Assistant to coordinate some actions on devices and to notify the status of the session. Now the last payload of each topic is retained. If by chance Home Assistant restarts those actions trigger the automations commanded by those topics even days later. This turns out to be very dangerous because it activates devices that should instead remain off in the absence of an active session. The same thing happened to me last night when an error notification started for a topic retain that happened two days ago. The cause was a restart of Home Assistant after the usual docker server backup. It would be really appreciated if the retain could be configurable from user interface when entering the Publish to MQTT broker command. The option to send a 0 byte payload for each of the topics used within the sequence would be a bloodbath and add unnecessary complexity. I thank you and salute

**Comment by daleghent** [comment]
Ok. In the designs I work with, the subscriber that cares about a certain message that is published to a topic is always connected. That process then clears the message via 0-byte payload when it has completed the work that was triggered. If the subscriber is not connected and later connects, any existing (uncleared) message older than 5 minutes triggers a separate warning notification to me to let me know that something went wrong and should be checked on. It's a way to ensure that the consumer of certain messages is doing its job and the synchronous, purposeful clearing of a retained payload is the final indication that the job completed without problems within an expected timeframe. I don't use Home Assistant so I don't know if it has the ability to process things in this manner; all my processing is via a mix of python, perl. and shell scripts I've made over the years.

But I can see your predicament if you are not actively clearing the messages. I have a beta of GS 3.0 available currently and will add an option for retention, with the default set to ON to maintain consistent behavior for other users. I'll put this in the next beta. You can access the beta by adding the NINA plugin beta channel URL under Options > General. The URL is: `https://nighttime-imaging.eu/wp-json/nina/v1/beta`

**Comment by giangitesta** [comment]
Thank you very much for your helpfulness and for considering the requirement.
Indeed being able to configure retain would add more flexibility to your already excellent plug-in.
Home Assistant is very flexible but managing such a thing would still be quite complex. I look forward to your release. Good work and again thank you very much!

**Comment by daleghent** [comment]
Ability to set/unset the retention flag is now in the new 3.0 beta 3 release.

**Comment by giangitesta** [comment]
Hi @daleghent,
thank you very much for your job.
I'm trying it out right now and everything seems to be working beautifully.
Best regards.
