### ISSUE TITLE
Pushover Emergency Alert setting

### ISSUE THREAD

**Issue by darkorb** [daleghent/nina-ground-station#2]
Firstly thanks for this plugin, it's helped me replace some pretty terrible scripts I had hanging around :)

In the plugin I note there is currently four options for Pushover notifications (Lowest, Low, Normal, High) however there is a fifth option provided by Pushover which is "Emergency" or 2 in the API. This is not one I can find in the plugin and sadly I've not been able to work out the way to add it to the code myself - though I could just be being blind and not spotting it as an option...

Would it be something you could add please if it is indeed not in already? The use case for this being that I make use of the focus settings on iOS to shush any other alerts that aren't important (like getting paged for work...) and it would be really helpful to have the failure notifications to be able to bypass this via the options for Critical Alerts on the Pushover app on iOS. That way it could still wake me by overriding the silent mode (toggle switch) and the software DND when things go bad.

**Comment by daleghent** [comment]
This is now in 1.14/2.1
